SELECT O.ORDER_ID, 
	   O.CUSTOMER_ID, 
	   O.EMPLOYEE_ID, 
	   O.ORDER_DATE, 
	   O.REQUIRED_DATE, 
	   O.SHIPPED_DATE, 
	   O.SHIP_VIA, 
	   O.FREIGHT, 
	   O.SHIP_NAME, 
	   O.SHIP_ADDRESS, 
	   O.SHIP_CITY, 
	   O.SHIP_REGION, 
	   O.SHIP_POSTAL_CODE, 
	   O.SHIP_COUNTRY, 
	   O.DATA_EXTRACAO,
	   D.ORDER_ID ,
	   D.PRODUCT_ID ,
	   D.UNIT_PRICE ,
	   D.QUANTITY ,
	   D.DISCOUNT 
FROM DW.SILVER.ORDERS O,
     DW.SILVER.ORDER_DETAILS D,
     DW.GOLD.DIM_CUSTOMERS C,
WHERE D.ORDER_ID 		= O.ORDER_ID 
AND   O.ORDER_ID 		= 10248
AND   C.CUSTOMER_ID 	= O.CUSTOMER_ID 




SELECT O.ORDER_ID, 
	   O.FREIGHT, 
	   ROUND((O.FREIGHT / count(*) OVER (PARTITION BY O.ORDER_ID)) ,2) FREIGHT_RATEADO,
	   D.ORDER_ID ,
	   D.PRODUCT_ID ,
	   D.UNIT_PRICE ,
	   D.QUANTITY ,
	   D.DISCOUNT 	   
FROM DW.SILVER.ORDERS O,
     DW.SILVER.ORDER_DETAILS D
WHERE D.ORDER_ID = O.ORDER_ID ;
AND   O.ORDER_ID = 10248;


SELECT DO.SK_ORDERS, 
	   DC.SK_CUSTOMER,
	   DE.SK_EMPLOYEE,  
	   DT.SK_DATA, 
	   OD.FREIGHT,
	   OT.
FROM DW.SILVER.ORDERS OD,
     DW.GOLD.DIM_ORDERS DO,
     DW.GOLD.DIM_CUSTOMERS DC,
     DW.GOLD.DIM_EMPLOYEES  DE,
     DW.GOLD.DIM_TEMPO DT,
     DW.SILVER.ORDER_DETAILS OT
WHERE OD.ORDER_ID 		= 10248
AND   DO.ORDER_ID       = OD.ORDER_ID 
AND   DC.CUSTOMER_ID 	= OD.CUSTOMER_ID
AND   DE.EMPLOYEE_ID 	= OD.EMPLOYEE_ID 
AND   DT."DATA" 	    = OD.ORDER_DATE 
AND   OT.ORDER_ID 		= OD.ORDER_ID 
 

 SELECT DO.SK_ORDERS, 
	   DC.SK_CUSTOMER,
	   DE.SK_EMPLOYEE,  
	   DT.SK_DATA, 
	   ROUND((OD.FREIGHT / count(*) OVER (PARTITION BY OD.ORDER_ID)) ,2) FREIGHT,
	   OT.QUANTITY,
	   OT.DISCOUNT 
FROM DW.SILVER.ORDERS OD,
     DW.GOLD.DIM_ORDERS DO,
     DW.GOLD.DIM_CUSTOMERS DC,
     DW.GOLD.DIM_EMPLOYEES  DE,
     DW.GOLD.DIM_TEMPO DT,
     DW.SILVER.ORDER_DETAILS OT
WHERE DO.ORDER_ID       = OD.ORDER_ID 
AND   DC.CUSTOMER_ID 	= OD.CUSTOMER_ID
AND   DE.EMPLOYEE_ID 	= OD.EMPLOYEE_ID 
AND   DT."DATA" 	    = OD.ORDER_DATE 
AND   OT.ORDER_ID 		= DO.ORDER_ID 
AND   OT.PRODUCT_ID 	= DO.PRODUCT_ID ;


