USE SCHEMA DW.GOLD;

CREATE OR REPLACE PROCEDURE DW.GOLD.PROC_DIM_SUPPLIERS()
RETURNS STRING
LANGUAGE SQL
AS
$$

BEGIN

    create TABLE IF NOT EXISTS DW.GOLD.DIM_SUPPLIERS (
        SK_SUPPLIER NUMBER AUTOINCREMENT,
        SUPPLIER_ID NUMBER(38,0) NOT NULL,
        COMPANY_NAME VARCHAR(40) NOT NULL,
        CONTACT_NAME VARCHAR(30),
        CONTACT_TITLE VARCHAR(30),
        ADDRESS VARCHAR(60),
        CITY VARCHAR(15),
        REGION VARCHAR(15),
        POSTAL_CODE VARCHAR(10),
        COUNTRY VARCHAR(15),
        PHONE VARCHAR(24),
        FAX VARCHAR(24),
        HOMEPAGE VARCHAR(16777216),
        DATA_EXTRACAO DATE
    );

    TRUNCATE TABLE DW.GOLD.DIM_SUPPLIERS;

    -- Inicia uma transação
    BEGIN TRANSACTION;

    INSERT INTO DW.GOLD.DIM_SUPPLIERS (SUPPLIER_ID, COMPANY_NAME, CONTACT_NAME, CONTACT_TITLE, ADDRESS, CITY, REGION, POSTAL_CODE, COUNTRY, PHONE, FAX, HOMEPAGE, DATA_EXTRACAO)
    SELECT SUPPLIER_ID, COMPANY_NAME, CONTACT_NAME, CONTACT_TITLE, ADDRESS, CITY, REGION, POSTAL_CODE, COUNTRY, PHONE, FAX, HOMEPAGE, DATA_EXTRACAO
    FROM DW.SILVER.SUPPLIERS;

    COMMIT;

    RETURN 'Dados inseridos com sucesso na tabela DIM_SUPPLIERS!';

EXCEPTION
    WHEN OTHER THEN
        -- Em caso de erro, realiza o rollback
        ROLLBACK;
        RETURN 'Erro durante a execução da procedure.';

END;
$$;

CALL DW.GOLD.PROC_DIM_SUPPLIERS();