USE SCHEMA DW.GOLD;

CREATE OR REPLACE PROCEDURE DW.GOLD.PROC_DIM_ORDERS()
RETURNS STRING
LANGUAGE SQL
AS
$$

BEGIN

    create TABLE IF NOT EXISTS DW.GOLD.DIM_ORDERS (
        SK_ORDERS NUMBER AUTOINCREMENT,
        ORDER_ID NUMBER(38,0) NOT NULL,
        PRODUCT_ID NUMBER(38,0),
        UNIT_PRICE FLOAT,
        REQUIRED_DATE DATE,
        SHIPPED_DATE DATE,
        SHIP_VIA NUMBER(38,0),
        SHIP_NAME VARCHAR(40),
        SHIP_ADDRESS VARCHAR(60),
        SHIP_CITY VARCHAR(15),
        SHIP_REGION VARCHAR(15),
        SHIP_POSTAL_CODE VARCHAR(10),
        SHIP_COUNTRY VARCHAR(15),
        DATA_EXTRACAO DATE
    );

    create or replace TABLE DW.GOLD.SHIPPERS (
        SHIPPER_ID NUMBER(38,0) NOT NULL,
        COMPANY_NAME VARCHAR(40) NOT NULL,
        PHONE VARCHAR(24),
        DATA_EXTRACAO DATE
    );

    TRUNCATE TABLE DW.GOLD.DIM_ORDERS;
    TRUNCATE TABLE DW.GOLD.SHIPPERS;

    -- Inicia uma transação
    BEGIN TRANSACTION;

    INSERT INTO DW.GOLD.DIM_ORDERS (
       ORDER_ID, 
       PRODUCT_ID, 
       UNIT_PRICE, 
	   REQUIRED_DATE, 
	   SHIPPED_DATE, 
	   SHIP_VIA, 
	   SHIP_NAME, 
	   SHIP_ADDRESS, 
	   SHIP_CITY, 
	   SHIP_REGION, 
	   SHIP_POSTAL_CODE, 
	   SHIP_COUNTRY, 
	   DATA_EXTRACAO )
    SELECT OD.ORDER_ID, 
        OT.PRODUCT_ID ,
        OT.UNIT_PRICE,
        OD.REQUIRED_DATE, 
        OD.SHIPPED_DATE, 
        OD.SHIP_VIA, 
        OD.SHIP_NAME, 
        OD.SHIP_ADDRESS, 
        OD.SHIP_CITY, 
        OD.SHIP_REGION, 
        OD.SHIP_POSTAL_CODE, 
        OD.SHIP_COUNTRY, 
        OD.DATA_EXTRACAO
    FROM DW.SILVER.ORDERS OD,
    	 DW.SILVER.ORDER_DETAILS OT
    WHERE OT.ORDER_ID  = OD.ORDER_ID 
    ORDER BY 1,2;


    INSERT INTO DW.GOLD.SHIPPERS (SHIPPER_ID, COMPANY_NAME, PHONE, DATA_EXTRACAO)
    SELECT SHIPPER_ID, COMPANY_NAME, PHONE, DATA_EXTRACAO
    FROM DW.SILVER.SHIPPERS;

    COMMIT;

    RETURN 'Dados inseridos com sucesso na tabela DIM_ORDERS!';

EXCEPTION
    WHEN OTHER THEN
        -- Em caso de erro, realiza o rollback
        ROLLBACK;
        RETURN 'Erro durante a execução da procedure.';

END;
$$;

CALL DW.GOLD.PROC_DIM_ORDERS();