USE SCHEMA DW.GOLD;

CREATE OR REPLACE PROCEDURE DW.GOLD.PROC_DIM_CUSTOMERS()
RETURNS STRING
LANGUAGE SQL
AS
$$

BEGIN

    create TABLE IF NOT EXISTS DW.GOLD.DIM_CUSTOMERS (
        SK_CUSTOMER NUMBER AUTOINCREMENT,
        CUSTOMER_ID VARCHAR(5) NOT NULL,
        COMPANY_NAME VARCHAR(40) NOT NULL,
        CONTACT_NAME VARCHAR(30),
        CONTACT_TITLE VARCHAR(30),
        ADDRESS VARCHAR(60),
        CITY VARCHAR(15),
        REGION VARCHAR(15),
        POSTAL_CODE VARCHAR(10),
        COUNTRY VARCHAR(15),
        PHONE VARCHAR(24),
        FAX VARCHAR(24),
        DATA_EXTRACAO DATE
    );

    TRUNCATE TABLE DW.GOLD.DIM_CUSTOMERS;

    -- Inicia uma transação
    BEGIN TRANSACTION;

    INSERT INTO DW.GOLD.DIM_CUSTOMERS (CUSTOMER_ID, COMPANY_NAME, CONTACT_NAME, CONTACT_TITLE, ADDRESS, CITY, REGION, POSTAL_CODE, COUNTRY, PHONE, FAX, DATA_EXTRACAO)
    SELECT CUSTOMER_ID, COMPANY_NAME, CONTACT_NAME, CONTACT_TITLE, ADDRESS, CITY, REGION, POSTAL_CODE, COUNTRY, PHONE, FAX, DATA_EXTRACAO
    FROM DW.SILVER.CUSTOMERS;

    COMMIT;

    RETURN 'Dados inseridos com sucesso na tabela DIM_CUSTOMERS!';

EXCEPTION
    WHEN OTHER THEN
        -- Em caso de erro, realiza o rollback
        ROLLBACK;
        RETURN 'Erro durante a execução da procedure.';

END;
$$;

CALL DW.GOLD.PROC_DIM_CUSTOMERS();