USE SCHEMA DW.GOLD;

CREATE OR REPLACE PROCEDURE DW.GOLD.PROC_DIM_EMPLOYEES()
RETURNS STRING
LANGUAGE SQL
AS
$$

BEGIN


    create or replace TABLE DW.GOLD.DIM_EMPLOYEES (
        SK_EMPLOYEE NUMBER AUTOINCREMENT,
        EMPLOYEE_ID NUMBER(38,0) NOT NULL,
        LAST_NAME VARCHAR(20) NOT NULL,
        FIRST_NAME VARCHAR(10) NOT NULL,
        TITLE VARCHAR(30),
        TITLE_OF_COURTESY VARCHAR(25),
        BIRTH_DATE DATE,
        HIRE_DATE DATE,
        ADDRESS VARCHAR(60),
        CITY VARCHAR(15),
        REGION VARCHAR(15),
        POSTAL_CODE VARCHAR(10),
        COUNTRY VARCHAR(15),
        HOME_PHONE VARCHAR(24),
        EXTENSION VARCHAR(4),
        NOTES VARCHAR(16777216),
        REPORTS_TO NUMBER(38,0),
        PHOTO_PATH VARCHAR(255),
        DATA_EXTRACAO DATE
    );

    create TABLE IF NOT EXISTS DW.GOLD.EMPLOYEE_TERRITORIES (
        EMPLOYEE_ID NUMBER(38,0) NOT NULL,
        TERRITORY_ID VARCHAR(20) NOT NULL,
        DATA_EXTRACAO DATE
    );    

    create TABLE IF NOT EXISTS DW.GOLD.TERRITORIES (
        TERRITORY_ID VARCHAR(20) NOT NULL,
        TERRITORY_DESCRIPTION VARCHAR(60) NOT NULL,
        REGION_ID NUMBER(38,0) NOT NULL,
        DATA_EXTRACAO DATE
    );    

    create TABLE IF NOT EXISTS DW.GOLD.REGION (
        REGION_ID NUMBER(38,0) NOT NULL,
        REGION_DESCRIPTION VARCHAR(60) NOT NULL,
        DATA_EXTRACAO DATE
    );    

    TRUNCATE TABLE DW.GOLD.DIM_EMPLOYEES;
    TRUNCATE TABLE DW.GOLD.EMPLOYEE_TERRITORIES;
    TRUNCATE TABLE DW.GOLD.TERRITORIES;
    TRUNCATE TABLE DW.GOLD.REGION;

    -- Inicia uma transação
    BEGIN TRANSACTION;

    INSERT INTO DW.GOLD.DIM_EMPLOYEES (EMPLOYEE_ID, LAST_NAME, FIRST_NAME, TITLE, TITLE_OF_COURTESY, BIRTH_DATE, HIRE_DATE, ADDRESS, CITY, REGION, POSTAL_CODE, COUNTRY, HOME_PHONE, EXTENSION, NOTES, REPORTS_TO, PHOTO_PATH, DATA_EXTRACAO)
    SELECT EMPLOYEE_ID, LAST_NAME, FIRST_NAME, TITLE, TITLE_OF_COURTESY, BIRTH_DATE, HIRE_DATE, ADDRESS, CITY, REGION, POSTAL_CODE, COUNTRY, HOME_PHONE, EXTENSION, NOTES, REPORTS_TO, PHOTO_PATH, DATA_EXTRACAO
    FROM DW.SILVER.EMPLOYEES;

    INSERT INTO DW.GOLD.EMPLOYEE_TERRITORIES (EMPLOYEE_ID,TERRITORY_ID,DATA_EXTRACAO)    
    SELECT EMPLOYEE_ID, 
           TERRITORY_ID, 
        DATA_EXTRACAO
    FROM DW.SILVER.EMPLOYEE_TERRITORIES;

    INSERT INTO DW.GOLD.TERRITORIES (TERRITORY_ID,TERRITORY_DESCRIPTION,REGION_ID,DATA_EXTRACAO)       
    SELECT TERRITORY_ID, 
        TERRITORY_DESCRIPTION,
        REGION_ID,
        DATA_EXTRACAO
    FROM DW.SILVER.TERRITORIES;    

    INSERT INTO DW.GOLD.REGION (REGION_ID,REGION_DESCRIPTION,DATA_EXTRACAO)       
    SELECT REGION_ID,
        REGION_DESCRIPTION,
        DATA_EXTRACAO
    FROM DW.SILVER.REGION;

    COMMIT;

    RETURN 'Dados inseridos com sucesso na tabela DIM_EMPLOYEES!';

EXCEPTION
    WHEN OTHER THEN
        -- Em caso de erro, realiza o rollback
        ROLLBACK;
        RETURN 'Erro durante a execução da procedure.';

END;
$$;

CALL DW.GOLD.PROC_DIM_EMPLOYEES();